### ISSUE TITLE
Секция меню

### ISSUE THREAD

**Issue by igosheva** [iamcoderUA/burger#10]
menu-list__link -  это кликабельный элемент, а значит по семантике ссылка. У нее должно стоять свойство cursor: pointer

**Comment by igosheva** [comment]
menu-list__text - не пойму зачем там стили для opacity и transition-delay, они в данном случае не работают. И ширина добавляется к окнтенту не плавно. Можно при добавлении класса active изменять ширину на 100%, т.е. вынести это из js в css, тогда ширина будет увеличиваться плавно

**Comment by igosheva** [comment]
и когда указываешь свойство transition лучше прописывать первым аргументом к какому именно свойству ты задаешь эту скорость появления, либо тогда задаешь всем свойствам через ключевое слово all, например transition: all .7s;

**Comment by iamcoderUA** [comment]
все переходы четко работали на css, а когда добавил черновой вариант на JS - все, соответственно, и отпало...
