### ISSUE TITLE
Бага с всплывающим окном

### ISSUE THREAD

**Issue by igosheva** [iamcoderUA/burger#13]
При закрытии фансибокса страница сначала на долю секунды перескакивает на главный экран, потом возвращается к тому месту, где был фансибокс.
озможно причина в следующем: когда указываешь иетод preventDefault не забывай скобки ставить после метода.
Пример: e.preventDefault();

**Comment by iamcoderUA** [comment]
Точно, все дело в скобках. А я все думал, что же то неправильно...
