### ISSUE TITLE
SVG в футере

### ISSUE THREAD

**Issue by igosheva** [iamcoderUA/burger#9]
Зачем вынес fill в инлайновые стили для socials__icon?) можно же было в CSS прописать) инлайновые стили нужно прописывать в крайнем крайнем случае)

**Comment by igosheva** [comment]
footer-left__phone-icon - тоже самое)

**Comment by iamcoderUA** [comment]
в footer-left__phone-icon я вынес fill, чтобы можно было влиять на цвет иконки вместе с текстом.
